sudo: required
group: edge
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - pip install docker-compose
script:
  - docker info
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose up -d
  - sleep 3
  - docker exec trackit_web_1 python manage.py test