language: python
sudo: required
group: edge
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-engine
script:
  - docker -v
  - docker-compose -v
  - docker-compose up -d
  - docker-compose run web python manage.py migrate
