sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - pip install docker-compose
script:
  - docker info
  - docker -v
  - docker-compose -v
  - docker-compose up -d
  - docker-compose run web python manage.py migrate