version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
  web:
    build: .
    environment:
      C_FORCE_ROOT: "yes"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
