version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
  web:
    build: .
    environment:
      C_FORCE_ROOT: "yes"
    command: bash -c "sleep 7 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
