# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierMasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('slug_name', models.CharField(max_length=500, null=True)),
                ('carrier_id', models.CharField(max_length=100, unique=True)),
                ('carrier_url', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_url_tracking', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('pattern_regex', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'carrier',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=500, null=True)),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('imported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin_country', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_locality', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_raw_location', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_locality', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_raw_location', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_json_blob', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='not_found', max_length=100)),
                ('carrier', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CarrierMasterData')),
            ],
            options={
                'db_table': 'parcel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together=set([('carrier', 'parcel_id')]),
        ),
    ]
