# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_event_type', models.CharField(blank=True, max_length=500, null=True)),
                ('original_time', models.CharField(blank=True, max_length=500, null=True)),
                ('original_location', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('parsed_event_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AlterField(
            model_name='carriermasterdata',
            name='slug_name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='carrier',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CarrierMasterData'),
        ),
        migrations.AddField(
            model_name='event',
            name='parcel',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app.Parcel'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('parcel', 'original_event_type', 'parsed_event_time', 'original_location')]),
        ),
    ]
