# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160622_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
