# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_carrier_carrier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='carrier_countries_iso',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
