# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrier_carrier_countries_iso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
