# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_rawdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='original_event_type',
            new_name='event_localtion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='original_location',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='original_time',
            new_name='event_time',
        ),
    ]
