# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160715_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_localtion',
            new_name='event_location',
        ),
    ]
