# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160719_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Info Received'), (2, 'In transit'), (3, 'Out for Delivery'), (4, 'Delivered'), (5, 'Failed Attempt'), (6, 'Exception')], default=1)),
            ],
        ),
    ]
