# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_eventmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMaster',
        ),
        migrations.AddField(
            model_name='event',
            name='delivery_status',
            field=models.IntegerField(choices=[(1, 'Info Received'), (2, 'In transit'), (3, 'Out for Delivery'), (4, 'Delivered'), (5, 'Failed Attempt'), (6, 'Exception')], default=0),
        ),
    ]
