# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160723_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='delivery_status',
            field=models.IntegerField(choices=[(0, ''), (1, 'Info Received'), (2, 'In transit'), (3, 'Out for Delivery'), (4, 'Delivered'), (5, 'Failed Attempt'), (6, 'Exception')], default=0),
        ),
    ]
