# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160723_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='mapper',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
